config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'pages#home'

  resources :snippets do
    member do
      post 'like'
    end
  end

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :snippet

  validates_uniqueness_of :user, scope: :snippet
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  belongs_to :user
  has_many :likes
  validates :user_id, presence: true
  validates :name, presence: true, length: { minimum: 5, maximum: 100 }
  validates :summary, presence: true, length: { minimum: 5, maximum: 100 }
  validates :description, presence: true

  def thumbs_up_total
    self.likes.where(like: true).size
  end

  def thumbs_down_total
    self.likes.where(like: false).size

  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :snippets
  has_many :likes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # validates :name, length: { minimum: 3, maximum: 40 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_devise_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
  def configure_devise_parameters
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end

end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  before_action :set_snippet, only: [:show, :edit, :update, :like, :destroy]

  def index
    @snippets = Snippet.all
  end

  def show
    # @snippet = Snippet.find(params[:id])
  end

  def new
    @snippet = Snippet.new
  end

  def create
    @snippet = Snippet.new(snippet_params)
    # @snippet.user = User.find(1)
    @snippet.user = current_user

    if @snippet.save
      flash[:notice] = "Snippet has been created."
      redirect_to @snippet
    else
      flash.now[:alert] = "Snippet has not been created."
      render 'new'
    end

  end

  def edit
    # @snippet = Snippet.find(params[:id])
  end

  def update
    # @snippet = Snippet.find(params[:id])
    if @snippet.update(snippet_params)
      flash[:success] = "Snippet has been updated."
      redirect_to snippet_path(@snippet)
    else
      flash.now[:alert] = "Snippet has not been updated."
      render 'edit'
    end
  end

  def destroy
    @snippet.destroy
    flash[:notice] = "Snippet has been deleted."

    redirect_to @snippet
  end

  def like
    @snippet.user = current_user
    like = Like.create(like: params[:like], user: current_user, snippet: @snippet)
    if like.valid?
      flash[:success] = "Your selection was recorded"
      redirect_to :back
    else
      flash[:danger] = "You can only like/dislike a snippet once"
      redirect_to :back
    end
  end

  private

  def snippet_params
    params.require(:snippet).permit(:name, :summary, :description)
  end

  def set_snippet
    @snippet = Snippet.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size:80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.email, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <p>&copy; Snippets 2015</p>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, message| %>
        <div data-alert class="alert-box <%= key %>">
          <%= message %>
          <a href="#" class="close">&times;</a>
        </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="top-bar foundation-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
     <span data-tooltip class="has-tip" title="Add you code snippets here"><h1 class="show-for-small-only"><%= link_to "S", root_path %></h1></span>
     <span data-tooltip class="has-tip" title="Add you code snippets here"><h1 class="show-for-medium-only"><%= link_to "Snip", root_path %></h1></span>
     <span data-tooltip class="has-tip" title="Add you code snippets here"><h1 class="show-for-large-only"><%= link_to "Snippets", root_path %></h1></span>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>

  </ul>
  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li><%= link_to "About Us", "" %></li>
      <% unless user_signed_in? %>
            <li class="<%= 'active' if current_page?('/users/sign_up') %>">
              <%= link_to "Sign up", new_user_registration_path %>
            </li>
            <li class="<%= 'active' if current_page?('/users/sign_in') %>">
              <%= link_to "Sign in", new_user_session_path %>
            </li>
      <% end %>
      <% if user_signed_in? %>
          <li>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete  %>
          </li>
          <li><%= link_to "My Snippets", snippets_path %></li>
          <li><%= link_to "New Snippet", new_snippet_path %></li>
      <% end %>

    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div class="row">
      <div class="small-12 columns">
        <%= render 'layouts/messages' %>

        <%= yield %>
        <%= render 'layouts/footer' %>

      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="row">
  <div class="large-12 columns">
    <% unless user_signed_in? %>
      <div class="superman panel callout radius center">
        <h1>Welcome to Snippets</h1>
        <h2>It's a little ostentatious, but useful for important content.</h2>
        <%= link_to "Sign up now", "", class: "button round" %>
        <%= link_to "Browser Snippet Listing", snippets_path , class: "button round small" %>
      </div>
    <% end %>
    <% if user_signed_in? %>
        <div class="superman panel callout radius center">
          <h1>Signed in as <%= current_user.email %></h1>
          <h2>It's a little ostentatious, but useful for important content.</h2>
          <%= link_to "My Snippets", snippets_path, class: "button round" %>
          <%= link_to "New Snippet", new_snippet_path, class: "button round" %>
        </div>
    <% end %>
  </div>
</div>
<!--
<div class="row">
  <div class="large-4 columns">
    <h3 class="midrow">View Snippets as Guest User</h3>
    <h2 class="left">Browse and view snippets as a guest and Sign up later</h2>
    <p><%= link_to "Browser Snippet Listing", snippets_path , class: "button round small" %></p>
  </div>
  <div class="large-4 columns">
    <h3 class="midrow">View Snippets as Guest User</h3>
    <h2 class="left">Browse and view snippets as a guest and Sign up later</h2>
    <p><%= link_to "Browser Snippet Listing", "", class: "button round small" %></p>
  </div>
  <div class="large-4 columns">
    <h3 class="midrow">View Snippets as Guest User</h3>
    <h2 class="left">Browse and view snippets as a guest and Sign up later</h2>
    <p><%= link_to "Browser Snippet Listing", "", class: "button round small" %></p>
  </div>
</div> -->

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="large-12 columns">
      <div data-alert class="alert-box alert radius">
        <a href="#" class="close">&times;</a>
        <h5>Correct the following errors:</h5>
        <ul>
          <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="alert an"
  </div>
<% end %>

app/views/shared/_page_title.html.erb
<p>
  <h1><%= title %></h1>
  <hr>
</p>

app/views/snippets/_form.html.erb
<%= render 'shared/errors', obj: @snippet %>

<div class="row">
  <div class="panel small-8 columns large-centered">
    <%= form_for @snippet do |f| %>
      <div class="row">
        <div class="small-3 columns">
          <%= f.label :name, class: "right inline" %>
        </div>
        <div class="small-9 columns">
          <%= f.text_field :name %>
        </div>
      </div>
      <div class="row">
        <div class="small-3 columns">
          <%= f.label :summary, class: "right inline" %>
        </div>
        <div class="small-9 columns">
          <%= f.text_field :summary %>
        </div>
      </div>
      <div class="row">
        <div class="small-3 columns">
          <%= f.label :description, class: "right inline" %>
        </div>
        <div class="small-9 columns">
          <%= f.text_area :description %>
        </div>
      </div>

      <%= f.submit(@snippet.new_record? ? "Create Snippet" : "Edit Snippet", class: "button") %>

    <% end %>
  </div>
</div>

app/views/snippets/edit.html.erb
<%= render 'shared/page_title', title: "Edit Snippet" %>


<%= render 'form' %>

app/views/snippets/index.html.erb
<%= render 'shared/page_title', title: "All Snippets" %>
<% @snippets.each do |snippet| %>
  <div class="row">
    <div class="large-2 columns">
      <section class="snippet_info center">
        <%= gravatar_for snippet.user, size: 100 %>
        <p>User email:<br> <%= snippet.user.email %></p>
      </section>
    </div>
  <div class="large-10 columns panel">
    <h4><%= link_to snippet.name, snippet_path(snippet)%></h4>
    <p><%= snippet.summary %></p>
    <p>
      <span class="quiet"><small><%= time_ago_in_words(snippet.created_at) %> ago</small></span>
    </p>
    <div class="pull-right">
      <%= snippet.thumbs_up_total %>
      <%= link_to "+", like_snippet_path(snippet, like: true), method: :post, class: "button" %>
      &nbsp&nbsp&nbsp&nbsp
      <%= snippet.thumbs_down_total %>
      <%= link_to "-", like_snippet_path(snippet, like: false), method: :post, class: "button" %>
    </div>
  </div>
<% end %>
<hr>

app/views/snippets/new.html.erb
<%= render 'shared/page_title', title: "Create a new Snippet" %>


<%= render 'form' %>

app/views/snippets/show.html.erb
<%= render 'shared/page_title', title: @snippet.name %>

<div class="row">
  <div class="small-4 columns push-8 center">
    <%= gravatar_for @snippet.user, size: 200 %>
    <p>
      <h5>Brought to you by <%= @snippet.user.email %></h5>
    </p>
  </div>
  <div class="small-8 columns pull-4">
    <h3><%= @snippet.summary %></h3>
    <div class="panel">
      <p>
        <strong>Code:</strong>
      </p>
      <code>
        <%= @snippet.description %>
      </code>
      <div class="pull-right">
        <%= @snippet.thumbs_up_total %>
        <%= link_to "+", like_snippet_path(@recipe, like: true), method: :post, class: "button" %>
        &nbsp&nbsp&nbsp&nbsp
        <%= @snippet.thumbs_down_total %>
        <%= link_to "-", like_snippet_path(@recipe, like: false), method: :post, class: "button" %>
      </div>
    </div>
    <%= link_to "Edit this Snippet", edit_snippet_path(@snippet), class: "button right" %>

  </div>
</div>

<h5><%= link_to "Return to Snippets Listing", snippets_path, class: "button small" %></h5>